import { drizzle, type PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres, { type Sql } from 'postgres';
import * as schema from './schema';

/** Drizzle-wrapped Postgres handle shared by the repositories (with the underlying pool for shutdown). */
export type Database = PostgresJsDatabase<typeof schema> & { $client: Sql };

/** Open a pooled Postgres connection wrapped by Drizzle. */
export function openDatabase(url: string): Database {
  // Pool sized for ~50–100 concurrent read users: each authenticated request can hold a connection
  // for a few sequential queries, so 10 became the head-of-line ceiling under load. 25 stays well
  // under Postgres' default max_connections=100 (leaving room for the engine + ingest + admin) and
  // costs nothing extra. idle_timeout reaps connections after a quiet spell.
  const client = postgres(url, { max: 25, idle_timeout: 30, onnotice: () => {} });
  return drizzle(client, { schema }) as Database;
}

/** Apply pending SQL migrations (generated by drizzle-kit into `migrationsFolder`). */
export async function runMigrations(db: Database, migrationsFolder: string): Promise<void> {
  await migrate(db, { migrationsFolder });
}

/** Close the underlying connection pool (graceful shutdown). */
export async function closeDatabase(db: Database): Promise<void> {
  await db.$client.end({ timeout: 5 });
}
