import type { Metadata, Viewport } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { ServiceWorkerRegistrar } from '@/presentation/components/sw-registrar';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });
const mono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono-font', display: 'swap' });

export const metadata: Metadata = {
  title: 'Meteora LP Monitor',
  description: 'Real-time Meteora DLMM portfolio — live PnL, fees, ranges, on-chain.',
  // Single icon source: web/public/icon.svg (generated by scripts/icons/build-icons.mjs).
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
    apple: '/apple-icon.png',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#14161b', // matches --color-bg so the mobile browser chrome blends in
  viewportFit: 'cover', // draw under notch / home indicator; safe-area insets handle padding
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body className="min-h-dvh">
        <ServiceWorkerRegistrar />
        {children}
      </body>
    </html>
  );
}
